#Site settings
theme: jekyll-theme-architect
title: Eiffy Luo
SEO title: Eiffy Luo
email: eiffyluo@gmail.com
description: BLOG
url: "eiffyluo.github.io"
#Sidebar settings
sidebar: true
sidebar-about-description: Educator| Writer
